version: "3.7"
services:
  metal_bat_db:
    image: postgres:12.8-alpine
    container_name: "metal-bat-db"
    restart: always
    environment:
      - POSTGRES_DB=metal_bat_db
      - POSTGRES_USER=mikel
      - POSTGRES_PASSWORD=secret
    volumes:
      - metal_bat_data:/var/lib/postgresql/data
    ports:
      - "5000:5432"
volumes:
  metal_bat_data:
    driver: local
